### ISSUE TITLE
Enable ENV vars to override some settings

### ISSUE THREAD

**Issue by datadavev** [arks-org/arks.github.io#3]
It is necessary to override a couple config values for service the site at a root. In particular, `_config.yml`
```
domain: arks-org.github.io
baseurl: /arks.github.io
url: https://arks-org.github.io
```
values need to be replaced. Can we enable these to be overridden by environment variables or something similar?

**Comment by whicks1** [comment]
In local build context, something along the lines of
```
bundle exec jekyll serve --config _config.yml,_config.local.yml
```
